### ISSUE TITLE
iOS跳转到聊天界面后返回按钮文字不显示

### ISSUE THREAD

**Issue by gzh4213** [qiyukf/react-native-qiyu#2]
![qq20170112-0](https://cloud.githubusercontent.com/assets/19168944/21885096/2b2a79ec-d8f1-11e6-9c4f-ee282045a65f.png)

**Comment by cyperus** [comment]
@Juice4213 请问你是解决了这个问题了吗？

**Comment by stlemon** [comment]
同上，我也是，怎么搞？
